### ISSUE TITLE
Development Run

### ISSUE THREAD

**Issue by CodexOS** [losbiw/erin#13]
I tried deleting the electron module and running yarn install, but continue to get the same error. I'm using Macbook M1 with Big Sur.

yarn electron-start
yarn run v1.22.11
$ electron .
Desktop/Photom/node_modules/electron/index.js:14
    throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
    ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at getElectronPath (Desktop/Photom/node_modules/electron/index.js:14:11)
    at Object.<anonymous> (Desktop/Photom/node_modules/electron/index.js:18:18)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (Desktop/Photom/node_modules/electron/cli.js:3:16)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by losbiw** [comment]
Hi, thanks for reporting the issue. As far as I'm concerned, electron is not supported by M1 devices out of the box, so you could try either one of these options
1) Run ```yarn upgrade``` and see if that fixes the issue
2) Otherwise, check out this link since it might come handy
https://www.reddit.com/r/electronjs/comments/m4tzyn/electron_on_m1_mac/?utm_medium=android_app&utm_source=share

**Comment by CodexOS** [comment]
Followed the steps in the link you've provided and got this error.
<img width="258" alt="Screen Shot 2021-09-01 at 3 14 39 PM" src="https://user-images.githubusercontent.com/51534682/131738754-947a06a0-4387-40bf-b84d-4001f507e364.png">

**Comment by losbiw** [comment]
Oh god, sorry, I just realized that I had forgotten to update README after adding quite a few changes to the build process. All you need to do is run ```yarn electron-compile``` and everything should work like a charm

**Comment by CodexOS** [comment]
I also tried running this in Windows and this is what I got. The window did open for the application, but I got this error in the development mode.

\Desktop\erin>yarn electron-start
yarn run v1.22.5
$ electron .

[2580:0901/172317.218:ERROR:CONSOLE(1)] "Uncaught TypeError: Cannot read property 'instance' of undefined", source: devtools://devtools/bundled/devtools_app.html?remoteBase=https://chrome-devtools-frontend.appspot.com/serve_file/@472e51ed20308c1f3cbd8706286e998fe511b4e/&can_dock=true&toolbarColor=rgba(223,223,223,1)&textColor=rgba(0,0,0,1)&experiments=true (1)



(This is what opened with the application Window)

electron/js2c/renderer_init.js:111 Electron Security Warning (Insecure Content-Security-Policy) This renderer process has either no Content Security
    Policy set or a policy with "unsafe-eval" enabled. This exposes users of
    this app to unnecessary security risks.

For more information and help, consult
https://electronjs.org/docs/tutorial/security.
This warning will not show up
once the app is packaged.

**Comment by losbiw** [comment]
Honestly, I don't really know what could go wrong with the mac version and either way it's not really a project related issue.
But speaking of windows one, those are not errors but warning
1) It's simply an issue with electron devtools, it always throws the "Uncaught TypeError: Cannot read property 'instance' of undefined" warning which I'm not really sure if it's possible to fix
2) If I'm not mistaking, the "unsafe-eval" is required to run React.js inside Electron, so once again, this is not exactly a project related issue
If you wanna get your MacOS version running, you could try messing around with packages versions, but I can't really help you with that. Thanks for reporting those issues, but I'm gonna close the issue now.
